### ISSUE TITLE
Module not found: fact_check

### ISSUE THREAD

**Issue by tomhosking** [jimmycode/gen-debiased-nli#2]
When running the provided command to fine tune a model, I get the following error:

```
python scripts/train_nli_synthetic.py \
  --exp_name bert-base_mnli_z-aug \
  --train_data data/gen-debiased-nli/mnli_z-aug \
  --dev_data data/MNLIMatchedHardWithHardTest --data_dir data/ \
  --model_name_or_path bert-base-uncased \
  --max_length 128 --per_device_train_batch_size 32 --per_device_eval_batch_size 16 \
  --learning_rate 1e-5 --num_train_epochs 5 --lr_scheduler_type constant_with_warmup --num_warmup_steps 2000 \
  --output_dir ./output/ \
  --seed 42 --do_predict --do_train
```

```
Traceback (most recent call last):
  File "scripts/train_nli_synthetic.py", line 43, in <module>
    from gen_debiased_nli.data.nli import load_all_nli_eval_datasets, eval_nli_predictions, get_nli_dataset
  File "/mnt/ext/phd/external/gen-debiased-nli/gen_debiased_nli/data/__init__.py", line 3, in <module>
    from .fact_check import ALL_FC_NAMES, get_fc_dataset
ModuleNotFoundError: No module named 'gen_debiased_nli.data.fact_check'
```

**Comment by tomhosking** [comment]
Seems that `fact_check` isn't needed anyway - PR #3 fixes this and a few other problems

**Comment by jimmycode** [comment]
Thanks Tom for fixing this. Pull request merged.
